### ISSUE TITLE
Run error in SEM forests using lavaan

### ISSUE THREAD

**Issue by PFernandez-Cancer** [brandmaier/semtree#55]
Hi Andreas. I found a run error that appears when lavaan-based SEM forests are parallelized using the plan(multisession) function from the package future. It works fine when future is not used.

[issue_future_lavaan.txt](https://github.com/brandmaier/semtree/files/11799084/issue_future_lavaan.txt)

**Comment by brandmaier** [comment]
Thank you for your report! I will look into this and get back to you.

**Comment by brandmaier** [comment]
Your code example works fine with the current version of the repository (https://github.com/brandmaier/semtree/commit/257bcd3c8c48e0158164394eaf58d3624f9242b5). Could you please provide the error messages?

**Comment by PFernandez-Cancer** [comment]
Hi Andreas. I installed semtree from your github and as you say it works perfectly fine. I'm currently using Manuel Arnold's github version, so maybe it's not 100% up to date. 

This is the error I was getting:
![error_message](https://github.com/brandmaier/semtree/assets/68905394/077d0272-be13-4faa-8626-feca4fdb3259)

I'll let Manuel know. Thanks!

**Comment by brandmaier** [comment]
Thank you!
