### ISSUE TITLE
Install package wrong in read me

### ISSUE THREAD

**Issue by LeonieHagitte** [brandmaier/semtree#57]
devtools::install_github("brandmaier/semtree")

# even better: install with package vignette (extra documentation)
devtools::install_github("brandmaier/semtree",force=TRUE, build_opts = c())

in the first line in the readme the name of repo and author are mixed up, which returns an error in R

**Comment by brandmaier** [comment]
Thanks @LeonieHagitte. Fixed as of https://github.com/brandmaier/semtree/commit/f439b98403ae40f29af6f9059972327b94be715b.
