### ISSUE TITLE
toTable doesn't appear to process round.param

### ISSUE THREAD

**Issue by knimon1** [brandmaier/semtree#60]
#See example below
#library(githubinstall)
#githubinstall("semtree",force=TRUE)

library(psychTools)
data(affect)

affect$Film <- factor(affect$Film, ordered = FALSE, 
                      labels=c("Frontline", "Halloween", "Nat. Geographic","Parenthood"))

tree.data <- affect[,c("Film","neur","ext","soc","traitanx","NA1","PA1")] 
tree.data$DeltaPA <- affect$PA2-affect$PA1

knitr::kable(head(tree.data))

library(OpenMx)
manifests<-c("DeltaPA")
latents<-c()
model <- mxModel("Simple Model", 
type="RAM",
manifestVars = manifests,
latentVars = latents,
mxPath(from="one",to=manifests, free=c(TRUE), value=c(1.0) , arrows=1, label=c("mu") ),
mxPath(from=manifests,to=manifests, free=c(TRUE), value=c(1.0) , arrows=2, label=c("sigma2") ),
mxData(tree.data, type = "raw")
);

result <- mxRun(model)

library(semtree)
ctrl = semtree.control(
  method="score", 
  bonferroni = TRUE)
tree = semtree( model = result, 
                data = tree.data, 
                control=ctrl)

toTable(tree,round.param=0)
toTable(tree,round.param=12)

**Comment by brandmaier** [comment]
The rounding is only for parameter estimates. By default, `toTable()` does not show any parameter estimates unless they are given as a vector of parameter names with argument `added.param.cols`, which is somewhat unintuitive. I now changed the default such that toTable() shows _all_ parameter estimates. Please download https://github.com/brandmaier/semtree/commit/456bb97eae768c98c85f61d326c559a2cb1ea42f or the latest version of semtree from here.
